# Generated by Django 5.2.7 on 2025-10-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_completado',
            field=models.DateTimeField(null=True),
        ),
    ]
