# Generated by Django 5.2.7 on 2025-10-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_fecha_completado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fecha_completado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
